### ISSUE TITLE
Repeatable on CentOS?

### ISSUE THREAD

**Issue by BrushXue** [utensils/docker-opengl#6]
Hello. I wish to run a 3D software what requires RHEL/CentOS 7. I want to create a CentOS 7 image with llvmpipe integrated so that the 3D software can run in headless servers. Seems like your image is the closest one to what I need. So is the building script repeatable on other Linux distributions? Thanks.

**Comment by BrushXue** [comment]
No one's replying so I managed to compile it myself

**Comment by doomspork** [comment]
Howdy @BrushXue! We've all been very busy but glad you got this sorted out.

**Comment by BrushXue** [comment]
Hello. Yes I kind of sorted out the installation steps. However the performance is really bad (only 1 core is enabled in llvmpipe for some reason). It must be a docker issue because in virtualbox it can utilize all cores.
